### PR TITLE
Use host's DNS servers

### PR DESCRIPTION
**Pull request by edigaryev**
Might help the users who are having issues with local DNS/VPN servers.

See https://github.com/cirruslabs/orchard/issues/92.

### CODE REVIEW

**Review by fkorotkov — APPROVED** [review]

**Comment by JulianH** [comment]
Hi @edigaryev, 

this issue is a blocker for us, as our gitlab is resolved only by an internal DNS server.
Is there any chance, to publish a new xcode-14 image containing this fix?

Thank you very much!

**Comment by edigaryev** [comment]
>Is there any chance, to publish a new xcode-14 image containing this fix?

Pinging @fkorotkov.

**Comment by fkorotkov** [comment]
@JulianH you can reset the setting by running the following command first thing in your CI script:

```bash
sudo networksetup -setdnsservers Ethernet "Empty"
```

**Comment by JulianH** [comment]
Hi @fkorotkov,

thanks for your quick reply. I want to use that images in the gitlab-tart-executor and the first step is, to clone the repository, which fails due to not able resolving the gitlab address.
If i manually run the vm, execute the script, then i can clone the repository, but not part of the Gitlab CI build job, unfortunately.

**Comment by fkorotkov** [comment]
Can you try [`pre_get_sources_script`](https://about.gitlab.com/blog/2023/03/27/changes-to-the-preclonescript/#what-is-the-pre_get_sources_script-hook)?

We usually update images on Saturdays to minimize impact of image distribution. If `pre_get_sources_script` doesn't work for you, we'll rebuild the latest Xcode 14+ image later this week.

**Comment by JulianH** [comment]
Hi @fkorotkov, thank you very much for this nice workaround, it is working 🚀

**Pull request merged**
