### PR TITLE
macOS 13.5.2

### PR DESCRIPTION
**Pull request by ruimarinho**

### CODE REVIEW

**Review by fkorotkov — APPROVED** [review]

**Review by edigaryev — APPROVED** [review]

**Comment by ruimarinho** [comment]
@fkorotkov will this image get published with actions runners 0.209.0?

**Comment by ruimarinho** [comment]
@fkorotkov can you push this update to `ghcr.io/cirruslabs/macos-ventura-xcode:14.3.1` please? The master branch only appears to build for sonoma.

**Comment by fkorotkov** [comment]
@ruimarinho we are working on a better way of mounting always the latest version of the GHA runner. In the meantime does auto-upgrade works for you? It adds a little delay in the beginning but works for us for Cirrus Runners.

**Comment by ruimarinho** [comment]
Right now 0.208.0 is fine looking at the changelog - 0.209.0 doesn't offer anything substantial ✌️ the auto-upgrade can now be disabled and saves a few seconds when launching VMs, so we'll keep it this way until your auto-updates come in. Looking forward to see that! Thank you.

**Pull request merged**
